package com.iti.jets.reportingsystem.entities;
// Generated Jun 2, 2021, 9:20:41 PM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.*;
import java.util.Date;

/**
 * FluidLevelMeasurments generated by hbm2java
 */
@Entity
@Table(name="fluid_level_measurements"
    ,catalog="reportingsystem"
)
public class FluidLevelMeasurements implements java.io.Serializable {


     private int id;
     private Well well;
     private Date date;
     private String intervals;
     private String fltype;
     private Double fluidLevel;
     private Double pumpDepth;
     private Long liqPercentage;
     private Long pumpFillage;
     private Double pumpSubmerge;
     private Character card;
     private String remarks;

    public FluidLevelMeasurements() {
    }

	
    public FluidLevelMeasurements(int id, Well well) {
        this.id = id;
        this.well = well;
    }
    public FluidLevelMeasurements(int id, Well well, Date date, String intervals, String fltype, Double fluidLevel, Double pumpDepth, Long liqPercentage, Long pumpFillage, Double pumpSubmerge, Character card, String remarks) {
       this.id = id;
       this.well = well;
       this.date = date;
       this.intervals = intervals;
       this.fltype = fltype;
       this.fluidLevel = fluidLevel;
       this.pumpDepth = pumpDepth;
       this.liqPercentage = liqPercentage;
       this.pumpFillage = pumpFillage;
       this.pumpSubmerge = pumpSubmerge;
       this.card = card;
       this.remarks = remarks;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="well_id", nullable=false)
    public Well getWell() {
        return this.well;
    }
    
    public void setWell(Well well) {
        this.well = well;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="intervals", length=200)
    public String getIntervals() {
        return this.intervals;
    }
    
    public void setIntervals(String intervals) {
        this.intervals = intervals;
    }

    
    @Column(name="fL_type", length=7)
    public String getFltype() {
        return this.fltype;
    }
    
    public void setFltype(String fltype) {
        this.fltype = fltype;
    }

    
    @Column(name="fluid_level", precision=22, scale=0)
    public Double getFluidlLevel() {
        return this.fluidLevel;
    }
    
    public void setFluidlLevel(Double fluidlLevel) {
        this.fluidLevel = fluidlLevel;
    }

    
    @Column(name="pump_depth", precision=22, scale=0)
    public Double getPumpDepth() {
        return this.pumpDepth;
    }
    
    public void setPumpDepth(Double pumpDepth) {
        this.pumpDepth = pumpDepth;
    }

    
    @Column(name="liq_percentage", precision=10, scale=0)
    public Long getLiqPercentage() {
        return this.liqPercentage;
    }
    
    public void setLiqPercentage(Long liqPercentage) {
        this.liqPercentage = liqPercentage;
    }

    
    @Column(name="pump_fillage", precision=10, scale=0)
    public Long getPumpFillage() {
        return this.pumpFillage;
    }
    
    public void setPumpFillage(Long pumpFillage) {
        this.pumpFillage = pumpFillage;
    }

    
    @Column(name="pump_submerge", precision=22, scale=0)
    public Double getPumpSubmerge() {
        return this.pumpSubmerge;
    }
    
    public void setPumpSubmerge(Double pumpSubmerge) {
        this.pumpSubmerge = pumpSubmerge;
    }

    
    @Column(name="card", length=1)
    public Character getCard() {
        return this.card;
    }
    
    public void setCard(Character card) {
        this.card = card;
    }

    
    @Column(name="remarks", length=2000)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


