package com.iti.jets.reportingsystem.entities;
// Generated Jun 7, 2021, 4:22:33 AM by Hibernate Tools 6.0.0.Alpha2


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ShutinTypeLevel2 generated by hbm2java
 */
@Entity
@Table(name="shutin_type_level2"
    ,catalog="reportingsystem"
)
public class ShutinTypeLevel2  implements java.io.Serializable {


     private Integer id;
     private ShutinType shutinType;
     private String description;
     private Set<ShutinTypeLevel3> shutinTypeLevel3s = new HashSet<ShutinTypeLevel3>(0);

    public ShutinTypeLevel2() {
    }

	
    public ShutinTypeLevel2(String description) {
        this.description = description;
    }
    public ShutinTypeLevel2(ShutinType shutinType, String description, Set<ShutinTypeLevel3> shutinTypeLevel3s) {
       this.shutinType = shutinType;
       this.description = description;
       this.shutinTypeLevel3s = shutinTypeLevel3s;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sh_id")
    public ShutinType getShutinType() {
        return this.shutinType;
    }
    
    public void setShutinType(ShutinType shutinType) {
        this.shutinType = shutinType;
    }

    
    @Column(name="description", nullable=false, length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shutinTypeLevel2")
    public Set<ShutinTypeLevel3> getShutinTypeLevel3s() {
        return this.shutinTypeLevel3s;
    }
    
    public void setShutinTypeLevel3s(Set<ShutinTypeLevel3> shutinTypeLevel3s) {
        this.shutinTypeLevel3s = shutinTypeLevel3s;
    }




}


