package com.iti.jets.reportingsystem.entities;
// Generated Jun 7, 2021, 4:22:33 AM by Hibernate Tools 6.0.0.Alpha2


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ShutinTypeLevel4 generated by hbm2java
 */
@Entity
@Table(name="shutin_type_level4"
    ,catalog="reportingsystem"
)
public class ShutinTypeLevel4  implements java.io.Serializable {


     private Integer id;
     private ShutinTypeLevel3 shutinTypeLevel3;
     private String description;
     private Set<DailyActions> dailyActionses = new HashSet<DailyActions>(0);

    public ShutinTypeLevel4() {
    }

	
    public ShutinTypeLevel4(ShutinTypeLevel3 shutinTypeLevel3, String description) {
        this.shutinTypeLevel3 = shutinTypeLevel3;
        this.description = description;
    }
    public ShutinTypeLevel4(ShutinTypeLevel3 shutinTypeLevel3, String description, Set<DailyActions> dailyActionses) {
       this.shutinTypeLevel3 = shutinTypeLevel3;
       this.description = description;
       this.dailyActionses = dailyActionses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sh_id_level3", nullable=false)
    public ShutinTypeLevel3 getShutinTypeLevel3() {
        return this.shutinTypeLevel3;
    }
    
    public void setShutinTypeLevel3(ShutinTypeLevel3 shutinTypeLevel3) {
        this.shutinTypeLevel3 = shutinTypeLevel3;
    }

    
    @Column(name="description", nullable=false, length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shutinTypeLevel4")
    public Set<DailyActions> getDailyActionses() {
        return this.dailyActionses;
    }
    
    public void setDailyActionses(Set<DailyActions> dailyActionses) {
        this.dailyActionses = dailyActionses;
    }




}


