package com.iti.jets.reportingsystem.entities;
// Generated Jun 2, 2021, 9:20:41 PM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.*;

/**
 * Userdata generated by hbm2java
 */
@Entity
@Table(name="userdata"
    ,catalog="reportingsystem"
)
public class Userdata  implements java.io.Serializable {


     private int id;
     private UserRoles userroles;
     private String firstName;
     private String lastName;
     private String email;
     private String phoneNumber;
     private String jobLocation;

    public Userdata() {
    }

	
    public Userdata(int id, UserRoles userroles) {
        this.id = id;
        this.userroles = userroles;
    }
    public Userdata(int id, UserRoles userroles, String firstName, String lastName, String email, String phoneNumber, String jobLocation) {
       this.id = id;
       this.userroles = userroles;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.jobLocation = jobLocation;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jobTitle", nullable=false)
    public UserRoles getUserroles() {
        return this.userroles;
    }
    
    public void setUserroles(UserRoles userroles) {
        this.userroles = userroles;
    }

    
    @Column(name="firstName", length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="lastName", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phoneNumber", length=45)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="jobLocation", length=7)
    public String getJobLocation() {
        return this.jobLocation;
    }
    
    public void setJobLocation(String jobLocation) {
        this.jobLocation = jobLocation;
    }




}


