package com.iti.jets.reportingsystem.entities;
// Generated Jun 2, 2021, 9:20:41 PM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * Userroles generated by hbm2java
 */
@Entity
@Table(name="userroles"
    ,catalog="reportingsysschema"
)
public class UserRoles implements java.io.Serializable {


     private int id;
     private String role;
     private Set<Userdata> userdatas = new HashSet<Userdata>(0);

    public UserRoles() {
    }

	
    public UserRoles(int id) {
        this.id = id;
    }
    public UserRoles(int id, String role, Set<Userdata> userdatas) {
       this.id = id;
       this.role = role;
       this.userdatas = userdatas;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="role", length=100)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="userroles")
    public Set<Userdata> getUserdatas() {
        return this.userdatas;
    }
    
    public void setUserdatas(Set<Userdata> userdatas) {
        this.userdatas = userdatas;
    }




}


