package com.iti.jets.reportingsystem.entities;
// Generated Jun 7, 2021, 4:22:33 AM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Userdata generated by hbm2java
 */
@Entity
@Table(name="userdata"
    ,catalog="reportingsystem"
)
public class Userdata  implements java.io.Serializable {


     private Integer id;
     private Userroles userroles;
     private String firstName;
     private String lastName;
     private String email;
     private String phoneNumber;
     private String jobLocation;
     private String password;

    public Userdata() {
    }

	
    public Userdata(Userroles userroles) {
        this.userroles = userroles;
    }
    public Userdata(Userroles userroles, String firstName, String lastName, String email, String phoneNumber, String jobLocation) {
       this.userroles = userroles;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.jobLocation = jobLocation;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="job_title", nullable=false)
    public Userroles getUserroles() {
        return this.userroles;
    }
    
    public void setUserroles(Userroles userroles) {
        this.userroles = userroles;
    }

    
    @Column(name="first_name", length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone_number", length=45)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="job_location", length=7)
    public String getJobLocation() {
        return this.jobLocation;
    }
    
    public void setJobLocation(String jobLocation) {
        this.jobLocation = jobLocation;
    }

    @Column(name="password", length=5000, nullable = false)
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }
}


