package com.iti.jets.reportingsystem.entities;
// Generated Jun 7, 2021, 4:22:33 AM by Hibernate Tools 6.0.0.Alpha2


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WellGeneralInfo generated by hbm2java
 */
@Entity
@Table(name="well_general_info"
    ,catalog="reportingsystem"
)


public class WellGeneralInfo  implements java.io.Serializable {


     private Integer id;
     private Well well;
     private String subCompanyName;
     private String locationName;
     private String areaName;
     private String leaseName;
     private String boreName;
     private Double xcord;
     private Double ycord;
     private Double lat;
     private Double longitude;

    public WellGeneralInfo() {
    }

	
    public WellGeneralInfo(Well well) {
        this.well = well;
    }
    public WellGeneralInfo(Well well, String subCompanyName, String locationName, String areaName, String leaseName, String boreName, Double XCord, Double YCord, Double lat, Double long_) {
       this.well = well;
       this.subCompanyName = subCompanyName;
       this.locationName = locationName;
       this.areaName = areaName;
       this.leaseName = leaseName;
       this.boreName = boreName;
       this.xcord = XCord;
       this.ycord = YCord;
       this.lat = lat;
       this.longitude = long_;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="well_id", nullable=false)
    public Well getWell() {
        return this.well;
    }
    
    public void setWell(Well well) {
        this.well = well;
    }

    
    @Column(name="sub_company_name", length=100)
    public String getSubCompanyName() {
        return this.subCompanyName;
    }
    
    public void setSubCompanyName(String subCompanyName) {
        this.subCompanyName = subCompanyName;
    }

    
    @Column(name="location_name", length=8)
    public String getLocationName() {
        return this.locationName;
    }
    
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }

    
    @Column(name="area_name", length=100)
    public String getAreaName() {
        return this.areaName;
    }
    
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    
    @Column(name="lease_name", length=100)
    public String getLeaseName() {
        return this.leaseName;
    }
    
    public void setLeaseName(String leaseName) {
        this.leaseName = leaseName;
    }

    
    @Column(name="bore_name", length=100)
    public String getBoreName() {
        return this.boreName;
    }
    
    public void setBoreName(String boreName) {
        this.boreName = boreName;
    }

    
    @Column(name="x_cord", precision=22, scale=0)
    public Double getXcord() {
        return this.xcord;
    }
    
    public void setXcord(Double XCord) {
        this.xcord = XCord;
    }

    
    @Column(name="y_cord", precision=22, scale=0)
    public Double getYcord() {
        return this.ycord;
    }
    
    public void setYcord(Double YCord) {
        this.ycord = YCord;
    }

    
    @Column(name="lat", precision=22, scale=0)
    public Double getLat() {
        return this.lat;
    }
    
    public void setLat(Double lat) {
        this.lat = lat;
    }

    
    @Column(name="longitude", precision=22, scale=0)
    public Double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(Double long_) {
        this.longitude = long_;
    }




}


