package com.iti.jets.reportingsystem.entities;
// Generated Jun 7, 2021, 4:22:33 AM by Hibernate Tools 6.0.0.Alpha2


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WellTestData generated by hbm2java
 */
@Entity
@Table(name="well_test_data"
    ,catalog="reportingsystem"
)
@JsonIdentityInfo(
        generator = ObjectIdGenerators.PropertyGenerator.class,
        property = "id")
public class WellTestData  implements java.io.Serializable {


     private Integer id;
    @JsonBackReference
     private Well well;
     private Date productionDate;
     private Integer TDuration;
     private Double gross;
     private Double net;
     private Double wc;
     private Double gor;
     private Double gasRate;
     private Double condensate;
     private Double whp;
     private Double wht;
     private Double usp;
     private Double ust;
     private Double sp;
     private Double st;
     private Double flp;
     private Double flt;
     private String chockType;
     private Integer chockSize;
     private Double h2s;
     private Double co2;
     private String unit;
     private String remarks;

    public WellTestData() {
    }

	
    public WellTestData(Well well) {
        this.well = well;
    }
    public WellTestData(Well well, Date productionDate, Integer TDuration, Double gross, Double net, Double wc, Double gor, Double gasRate, Double condensate, Double whp, Double wht, Double usp, Double ust, Double sp, Double st, Double flp, Double flt, String chockType, Integer chockSize, Double h2s, Double co2, String unit, String remarks) {
       this.well = well;
       this.productionDate = productionDate;
       this.TDuration = TDuration;
       this.gross = gross;
       this.net = net;
       this.wc = wc;
       this.gor = gor;
       this.gasRate = gasRate;
       this.condensate = condensate;
       this.whp = whp;
       this.wht = wht;
       this.usp = usp;
       this.ust = ust;
       this.sp = sp;
       this.st = st;
       this.flp = flp;
       this.flt = flt;
       this.chockType = chockType;
       this.chockSize = chockSize;
       this.h2s = h2s;
       this.co2 = co2;
       this.unit = unit;
       this.remarks = remarks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="well_id", nullable=false)
    public Well getWell() {
        return this.well;
    }
    
    public void setWell(Well well) {
        this.well = well;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="production_date", length=10)
    public Date getProductionDate() {
        return this.productionDate;
    }
    
    public void setProductionDate(Date productionDate) {
        this.productionDate = productionDate;
    }

    
    @Column(name="t_duration")
    public Integer getTDuration() {
        return this.TDuration;
    }
    
    public void setTDuration(Integer TDuration) {
        this.TDuration = TDuration;
    }

    
    @Column(name="gross", precision=22, scale=0)
    public Double getGross() {
        return this.gross;
    }
    
    public void setGross(Double gross) {
        this.gross = gross;
    }

    
    @Column(name="net", precision=22, scale=0)
    public Double getNet() {
        return this.net;
    }
    
    public void setNet(Double net) {
        this.net = net;
    }

    
    @Column(name="WC", precision=22, scale=0)
    public Double getWc() {
        return this.wc;
    }
    
    public void setWc(Double wc) {
        this.wc = wc;
    }

    
    @Column(name="GOR", precision=22, scale=0)
    public Double getGor() {
        return this.gor;
    }
    
    public void setGor(Double gor) {
        this.gor = gor;
    }

    
    @Column(name="gas_rate", precision=22, scale=0)
    public Double getGasRate() {
        return this.gasRate;
    }
    
    public void setGasRate(Double gasRate) {
        this.gasRate = gasRate;
    }

    
    @Column(name="condensate", precision=22, scale=0)
    public Double getCondensate() {
        return this.condensate;
    }
    
    public void setCondensate(Double condensate) {
        this.condensate = condensate;
    }

    
    @Column(name="WHP", precision=22, scale=0)
    public Double getWhp() {
        return this.whp;
    }
    
    public void setWhp(Double whp) {
        this.whp = whp;
    }

    
    @Column(name="WHT", precision=22, scale=0)
    public Double getWht() {
        return this.wht;
    }
    
    public void setWht(Double wht) {
        this.wht = wht;
    }

    
    @Column(name="USP", precision=22, scale=0)
    public Double getUsp() {
        return this.usp;
    }
    
    public void setUsp(Double usp) {
        this.usp = usp;
    }

    
    @Column(name="UST", precision=22, scale=0)
    public Double getUst() {
        return this.ust;
    }
    
    public void setUst(Double ust) {
        this.ust = ust;
    }

    
    @Column(name="SP", precision=22, scale=0)
    public Double getSp() {
        return this.sp;
    }
    
    public void setSp(Double sp) {
        this.sp = sp;
    }

    
    @Column(name="ST", precision=22, scale=0)
    public Double getSt() {
        return this.st;
    }
    
    public void setSt(Double st) {
        this.st = st;
    }

    
    @Column(name="FLP", precision=22, scale=0)
    public Double getFlp() {
        return this.flp;
    }
    
    public void setFlp(Double flp) {
        this.flp = flp;
    }

    
    @Column(name="FLT", precision=22, scale=0)
    public Double getFlt() {
        return this.flt;
    }
    
    public void setFlt(Double flt) {
        this.flt = flt;
    }

    
    @Column(name="chock_type", length=10)
    public String getChockType() {
        return this.chockType;
    }
    
    public void setChockType(String chockType) {
        this.chockType = chockType;
    }

    
    @Column(name="chock_size")
    public Integer getChockSize() {
        return this.chockSize;
    }
    
    public void setChockSize(Integer chockSize) {
        this.chockSize = chockSize;
    }

    
    @Column(name="h2s", precision=22, scale=0)
    public Double getH2s() {
        return this.h2s;
    }
    
    public void setH2s(Double h2s) {
        this.h2s = h2s;
    }

    
    @Column(name="co2", precision=22, scale=0)
    public Double getCo2() {
        return this.co2;
    }
    
    public void setCo2(Double co2) {
        this.co2 = co2;
    }

    
    @Column(name="unit", length=100)
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }

    
    @Column(name="remarks", length=5000)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


